baseURL = 'https://iteoe.github.io/'
languageCode = 'en-us'
title = 'IN THE EVENT OF AN EMERGENCY'
theme = 'holy'

[params]
  copyright = ""
  subtitle = 'ഒരു അടിയന്തരാവസ്ഥക്കാലത്ത്'

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10