baseURL = 'https://iteoe.github.io/'
languageCode = 'en-us'
title = 'In The Event Of Emergency'
theme = 'holy'

[params]
  copyright = ""

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10